name: CICD

on:
  push:
    branches: ['main']

defaults:
  run:
    working-directory: .

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          port: 22
          script: |
            # Update PATH to include the directory where node and npm are installed
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v16.13.1/bin
            cd missing-person-finder
            git pull
            echo $PATH
            which npm
            npm -v
            pm2 -v
            npm i
            pm2 restart 0
