name: Lint
on:
    push:
        branches:
            - master
            - main
    pull_request:
        - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/@checkoutv2

            - name: Install Dependencies
              run: npm i

            - name: Run lint
              run: npm run lint